# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for unified-diff-mcp

# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app
# Copy manifest and tsconfig
COPY package.json package-lock.json tsconfig.json ./
# Copy source
COPY src ./src
# Install dependencies and build with tsc
RUN npm install --ignore-scripts && \
    npm run build:node

# Runtime stage
FROM node:lts-alpine
WORKDIR /app
# Install runtime dependencies
COPY package.json package-lock.json ./
RUN npm install --only=production --ignore-scripts
# Install chromium for Playwright
RUN apk add --no-cache chromium nss
# Copy built files
COPY --from=builder /app/dist ./dist
# Set Chromium path
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
# Default command
CMD ["node", "dist/index.js"]
